### ISSUE TITLE
Write up vulnerabilities

### ISSUE THREAD

**Issue by dugdug36** [cerberauth/api-vulns-challenges#26]
Hello, 
Can you provide vulnerabilities write up about every vulnerabilities covered by your APP ?.

Its for DevSecOps awareness. 

Best regards

**Comment by emmanuelgautier** [comment]
Hello,

Thanks for you issue. You are right, it would be definitely useful.
You can find some [Vulnerability labs and their related explaination page](https://vulnapi.cerberauth.com/labs/).

Could share more about the context you are using this project? It can help be more specific writing vulnerabilities details.
